name: Build & push other images

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  build:
    # https://github.com/uwu/basic-env/blob/59d7e8d9b0328ffa59654eb8de79f200a930fcd6/.github/workflows/build-and-push-others.yml
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    
    strategy:
      matrix:
        template: [docker-android]
    
    env:
      IMAGE_NAME: ${{ matrix.template }}-env

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
        if: github.event_name != 'pull_request'

      - name: "Pre-build '${{ env.IMAGE_NAME }}' image"
        uses: devcontainers/ci@v0.3
        with:
          subFolder: ${{ matrix.template }}
          imageName: ${{ env.IMAGE_PATH }}
          cacheFrom: ${{ env.IMAGE_PATH }}
          push: ${{ github.event_name != 'pull_request' && 'always' || 'never' }}
        env:
          IMAGE_PATH: ghcr.io/${{ github.repository }}/${{ env.IMAGE_NAME }}